#!/bin/bash

#PBS -N R_JOB
#PBS -q comm_small_week
##PBS -j oe
#PBS -l nodes=1:ppn=40
#PBS -n
#PBS -M noemail@hpc.wvu.edu
##PBS -l prologue=/users/bprice5/prologue.sh
##PBS -l epilogue=/users/bprice5/epilogue.sh
#PBS -t 1-12

cd $PBS_O_WORKDIR
#module load general_intel19
module load general_gcc82

export OPENBLAS_NUM_THREADS=2

input=`cat sim1_run.txt| head -$PBS_ARRAYID | tail -1`

echo $input

./sim_1_crf_tf.R $input
